name = "mallam-backend"
main = "src/index.ts"
compatibility_date = "2023-10-25"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB_DATASETS"
database_name = "mallam-datasets"
database_id = "1fdbbadc-27c4-4fee-88d7-9d6d930c3f49"

[[queues.producers]]
binding = "QUEUE_DATASETS_VECTORIZE_SENTENCE_UPSERT"
queue = "mallam-datasets-vectorize-sentence-upsert"

[[queues.consumers]]
queue = "mallam-datasets-vectorize-sentence-upsert"


[[vectorize]]
binding = "VECTORIZE_DATASETS_SENTENCES"
index_name = "mallam-datasets-sentences"
