name = "mallam-backend"
main = "src/index.ts"
compatibility_date = "2023-12-01"
routes = [{ pattern = "api.mallam.ai", custom_domain = true }]

[ai]
binding = "AI"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB_MAIN"
database_name = "mallam-main"
database_id = "8ea16b21-7de0-4cd1-9a65-cf3d049639c0"

[[queues.producers]]
binding = "QUEUE_MAIN_DOCUMENT_ANALYZE"
queue = "mallam-main-document-analyze"

[[queues.consumers]]
queue = "mallam-main-document-analyze"
max_retries = 5

[[queues.producers]]
binding = "QUEUE_MAIN_SENTENCE_ANALYZE"
queue = "mallam-main-sentence-analyze"

[[queues.consumers]]
queue = "mallam-main-sentence-analyze"
max_retries = 5


[[vectorize]]
binding = "VECTORIZE_DATASETS_SENTENCES"
index_name = "mallam-datasets-sentences"

[[vectorize]]
binding = "VECTORIZE_MAIN_SENTENCES"
index_name = "mallam-main-sentences"
